### ISSUE TITLE
WGS project count different than expected

### ISSUE THREAD

**Issue by Phylloxera** [khyox/draftGenomes#1]
Hi,
Neat tool, looking forward to taking it for a test drive... Noticed that for bacterial projects, draftGenomes says there are 191660, while the following entrez query of Nucleotide on the NCBI website returns 515087 hits: "wgs master"[Properties] AND txid2[orgn] . Is the discrepancy because draftGenomes is excluding duplicate refseqs? I got an error on my third download and multiple attempts at using the -r flag did not help:
`./draftGenomes.py -r -t 2`
FAILED! Unexpected EOF while parsing file AAAD01.1.fsa_nt.gz. Is it corrupted?
NOTE: You can try to solve any issue and resume
         the process using the -r/--resume  flag.
Thanks!

**Comment by khyox** [comment]
Thank you very much for the report. This is two issues in one. 

The second one should be easy to solve so I start with that: Just remove the corrupted file from your filesystem (e.g. `rm AAAD01.1.fsa_nt.gz`) and resume DG with the `-r` flag enabled. To avoid accidental loss of data, DG is not removing any file except when the force flag is used, and it let such actions to the user.

The first issue is a big deal. Thank you very much for pointing out this. After some research, it seems that about half a year ago NCBI decided to introduce some (undocumented, TTBOMK) changes in the prefix of the WGS projects. The official page of the database (https://www.ncbi.nlm.nih.gov/genbank/wgs/) still indicates that:

> Each WGS project is assigned a stable 4-letter WGS accession prefix, which does not change as the project is updated. In addition to the WGS accession prefix, the contig identifiers have a version number corresponding to a particular WGS project update. Finally, each individual contig within the assembly is assigned a unique accession number prefixed by the WGS accession prefix and version number. For instance, if a WGS project's assigned accession number is XXXX00000000, then that project's first assembly version would be XXXX01000000, and the first contig of that version would be XXXX01000001. (The last six digits of this ID identify each individual contig). 

Recent projects are no longer compliant with this format (for example [WGS project AAJDPH01](https://www.ncbi.nlm.nih.gov/Traces/wgs/AAJDPJ01)). DG uses a CGI script on the NCBI servers to retrieve the list of projects, and it seems that the main problem should be there, with the CGI script unaware of the new undocumented format —it only returns projects compliant with the traditional documented format. 

I am contacting NCBI support to let them know about this major problem. I will keep you informed. In the meanwhile, take into account that DG is not providing data from the more recent projects.

**Comment by khyox** [comment]
Update: NCBI was not aware of this problem and they are now looking into fixing the CGI.

**Comment by khyox** [comment]
Update: NCBI reports that the CGI should be fixed now but it is to be updated on the public side of their servers, which is still pendent.

**Comment by khyox** [comment]
For future reference, this relates to NCBI Case #: CAS-408279-C9F6Y5

**Comment by Phylloxera** [comment]
Hello,

Wanted to send a quick update. I tried draftGenomes on Aug 30, 2019

It returns 130621 WGS projects to collect for tid 590 while the entrez query on the nucleotide ncbi website returns 141788 hits. The error is different too but I'll let you check that out yourself. Presumably the public-side updates are still pending as of Aug 30, 2019.

**Comment by khyox** [comment]
Sorry, no time for the major update required to keep this running after the important NCBI changes!
