### ISSUE TITLE
downloading the entire WGS

### ISSUE THREAD

**Issue by lpipes** [khyox/draftGenomes#3]
If I wanted to download the entire WGS into 1 fasta file. What command should I run? Also, can a blastn search be performed on the WGS database?

**Comment by khyox** [comment]
Hi Lenore, sorry for the late reply. When I released the code you were able to download the entire WGS db in a single fasta file, but recent changes in NCBI made this software unusable for retrieving new WGS projects. Unfortunately, as I am working now on a quite different topic, I have no time for the major changes required to update the code, so I have declared it "legacy software". Sorry!
